name: SonarCloud Automation

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      project:
        description: "Proyecto a analizar"
        required: true
        default: ""

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Execute automation script
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PROJECT_NAME: ${{ github.event.inputs.project }}
        run: |
          python automation/sonarcloud_automation.py

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ github.event.inputs.project }}
